export const SITE_CONFIG = {
  name: 'Murrieta Concrete Works',
  shortName: 'Concrete Murrieta',
  phone: '(951) 555-0303',
  email: 'info@murrietaconcreteworks.com',
  address: 'Murrieta, CA 92562',
  domain: 'https://murrietaconcreteworks.com',
  description: 'Expert concrete driveways, patios, and walkways in Murrieta, CA. Licensed contractors. Free estimates.',
  services: [
    { title: 'Concrete Driveways', href: '/services/concrete-driveways', description: 'Durable driveway installation and replacement.' },
    { title: 'Patios & Walkways', href: '/services/patios-walkways', description: 'Custom concrete patios and walkway installations.' },
    { title: 'Concrete Patios', href: '/services/concrete-patios', description: 'Custom patio slabs in standard, stamped, or exposed aggregate.' },
    { title: 'Walkways & Sidewalks', href: '/services/concrete-walkways-sidewalks', description: 'Residential walkway and sidewalk installation and repair.' },
    { title: 'Concrete Repair', href: '/services/concrete-repair', description: 'Crack repair and resurfacing for existing concrete.' },
    { title: 'Decorative Concrete', href: '/services/decorative-concrete', description: 'Stamped and stained concrete for curb appeal.' },
    { title: 'Concrete Walls', href: '/services/concrete-walls', description: 'Retaining walls, block walls, and garden walls.' },
    { title: 'Concrete Foundations', href: '/services/concrete-foundations', description: 'Garage slabs, ADU pads, and addition foundation pours.' },
    { title: 'Concrete Slabs', href: '/services/concrete-slabs', description: 'Shed pads, RV pads, shop floors, and equipment pads.' },
    { title: 'Concrete Pool Decks', href: '/services/concrete-pool-decks', description: 'Slip-resistant pool deck installations in exposed aggregate, stamped, or brushed finishes.' },
    { title: 'Concrete Sealing', href: '/services/concrete-sealing', description: 'Professional sealing to protect and extend the life of your concrete.' },
    { title: 'Mudjacking & Slab Leveling', href: '/services/mudjacking-slab-leveling', description: 'Lift and level sunken or settled concrete without full replacement.' },
  ],
  locations: [
    { city: 'Temecula', href: '/temecula' },
    { city: 'Wildomar', href: '/wildomar' },
    { city: 'Menifee', href: '/menifee' },
    { city: 'Hemet', href: '/hemet' },
    { city: 'Perris', href: '/perris' },
    { city: 'San Jacinto', href: '/san-jacinto' },
    { city: 'Fallbrook', href: '/fallbrook' },
    { city: 'Lake Elsinore', href: '/lake-elsinore' },
    { city: 'Canyon Lake', href: '/canyon-lake' },
  ],
};
