export const SITE_CONFIG = {
  name: 'Murrieta Landscaping',
  shortName: 'Landscaping Murrieta',
  phone: '(951) 555-0202',
  email: 'info@landscapingmurrieta.com',
  address: 'Murrieta, CA 92562',
  domain: 'https://landscapingmurrieta.com',
  description: 'Professional landscaping design, lawn care, and yard transformation in Murrieta, CA. Free consultations.',
  services: [
    { title: 'Landscape Design', href: '/services/landscape-design', description: 'Custom landscape plans tailored to Murrieta\'s climate.' },
    { title: 'Lawn Care', href: '/services/lawn-care', description: 'Regular maintenance to keep your lawn green year-round.' },
    { title: 'Irrigation Systems', href: '/services/irrigation', description: 'Water-efficient irrigation solutions for inland SoCal.' },
    { title: 'Seasonal Cleanup', href: '/services/seasonal-cleanup', description: 'Spring and fall yard cleanup to keep your property pristine.' },
    { title: 'Sod Installation', href: '/services/sod-installation', description: 'Professional sod laying for instant, lush lawns.' },
    { title: 'Mulching', href: '/services/mulching', description: 'Weed suppression and moisture retention with quality mulch.' },
    { title: 'Retaining Walls', href: '/services/retaining-walls', description: 'Durable retaining walls for slope control and curb appeal.' },
  ],
  locations: [
    { city: 'Temecula', href: '/temecula' },
    { city: 'Wildomar', href: '/wildomar' },
    { city: 'Menifee', href: '/menifee' },
    { city: 'Hemet', href: '/hemet' },
    { city: 'Perris', href: '/perris' },
    { city: 'San Jacinto', href: '/san-jacinto' },
    { city: 'Fallbrook', href: '/fallbrook' },
    { city: 'Lake Elsinore', href: '/lake-elsinore' },
    { city: 'Canyon Lake', href: '/canyon-lake' },
  ],
};
